name: Sync to Hugging face Hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push -f https://Joshagibby:$HF_TOKEN@https://huggingface.co/spaces/Joshagibby/Personal-Widget-Page
